---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      name: registration
      labels:
        app: registration
    spec:
      containers:
      - name: flask
        image: jaibw/app:1
        ports:
        - containerPort: 80
        env:
          - name: DB_HOST
            value: mysql-db
        envFrom:
          - secretRef:
              name: app-secrets
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: registration
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
  selector:
    app: registration